# Generated by Django 5.0.1 on 2025-10-18 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_slug",
                    models.CharField(
                        help_text="Slug do tenant consultado",
                        max_length=100,
                        verbose_name="Tenant Slug",
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Tenant"
                    ),
                ),
                (
                    "sensor_id",
                    models.CharField(
                        blank=True,
                        help_text="Sensor específico ou vazio para todos",
                        max_length=100,
                        verbose_name="Sensor ID",
                    ),
                ),
                (
                    "from_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Inicial"
                    ),
                ),
                (
                    "to_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Final"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID da task no Celery",
                        max_length=255,
                        verbose_name="Celery Task ID",
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True,
                        help_text="Link para download do CSV (MinIO/S3)",
                        max_length=500,
                        verbose_name="URL do Arquivo",
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do Arquivo (bytes)"
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total de linhas exportadas",
                        null=True,
                        verbose_name="Quantidade de Registros",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Arquivo será deletado após esta data (24h default)",
                        null=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Staff user que solicitou o export",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ops_exportj_user_id_0a8f0c_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="ops_exportj_status_6e9818_idx",
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="ops_exportj_celery__d76cae_idx"
                    ),
                ],
            },
        ),
    ]
