# Generated by Django 5.0.1 on 2025-10-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Backup caso usuário seja deletado",
                        max_length=150,
                        verbose_name="Nome de Usuário",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_list", "Visualizar Lista"),
                            ("view_drilldown", "Visualizar Detalhes"),
                            ("export_csv", "Export CSV Síncrono"),
                            ("export_async", "Export CSV Assíncrono"),
                            ("view_dashboard", "Visualizar Dashboard"),
                        ],
                        max_length=50,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "tenant_slug",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tenant Consultado"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Parâmetros da query (sensor_id, timestamps, etc)",
                        verbose_name="Filtros Aplicados",
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total de registros retornados/exportados",
                        null=True,
                        verbose_name="Quantidade de Registros",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tempo de Execução (ms)"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Executado em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Staff user que executou a ação",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ops_auditlo_user_id_8cd4d9_idx",
                    ),
                    models.Index(
                        fields=["tenant_slug", "-created_at"],
                        name="ops_auditlo_tenant__89c466_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="ops_auditlo_action_0ed456_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="ops_auditlo_created_00770a_idx"
                    ),
                ],
            },
        ),
    ]
