# Generated by Django 5.0.1 on 2025-10-31 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="duration",
            field=models.IntegerField(
                blank=True, default=5, null=True, verbose_name="Duração (deprecated)"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="operator",
            field=models.CharField(
                blank=True,
                choices=[
                    (">", "Maior que"),
                    (">=", "Maior ou igual"),
                    ("<", "Menor que"),
                    ("<=", "Menor ou igual"),
                    ("==", "Igual"),
                    ("!=", "Diferente"),
                ],
                max_length=10,
                null=True,
                verbose_name="Operador (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="parameter_key",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Chave do Parâmetro (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Critical", "Crítico"),
                    ("High", "Alto"),
                    ("Medium", "Médio"),
                    ("Low", "Baixo"),
                ],
                default="Medium",
                max_length=20,
                null=True,
                verbose_name="Severidade (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="threshold",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valor Limite (deprecated)"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="unit",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Unidade (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="variable_key",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Chave da Variável (deprecated)",
            ),
        ),
        migrations.CreateModel(
            name="RuleParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_key",
                    models.CharField(max_length=100, verbose_name="Chave do Parâmetro"),
                ),
                (
                    "variable_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Chave da Variável"
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (">", "Maior que"),
                            (">=", "Maior ou igual"),
                            ("<", "Menor que"),
                            ("<=", "Menor ou igual"),
                            ("==", "Igual"),
                            ("!=", "Diferente"),
                        ],
                        max_length=10,
                        verbose_name="Operador",
                    ),
                ),
                ("threshold", models.FloatField(verbose_name="Valor Limite")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="Unidade"),
                ),
                (
                    "duration",
                    models.IntegerField(default=5, verbose_name="Duração (minutos)"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Crítico"),
                            ("High", "Alto"),
                            ("Medium", "Médio"),
                            ("Low", "Baixo"),
                        ],
                        default="Medium",
                        max_length=20,
                        verbose_name="Severidade",
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Use {sensor}, {value}, {threshold}, {operator}, {unit} como variáveis",
                        verbose_name="Template da Mensagem",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="alerts.rule",
                        verbose_name="Regra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetro de Regra",
                "verbose_name_plural": "Parâmetros de Regra",
                "db_table": "alerts_ruleparameter",
                "ordering": ["rule", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["rule", "order"], name="alerts_rule_rule_id_0807b9_idx"
                    ),
                    models.Index(
                        fields=["parameter_key"], name="alerts_rule_paramet_c12a16_idx"
                    ),
                ],
            },
        ),
    ]
