# Generated by Django 5.0.1 on 2025-11-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0002_alter_rule_duration_alter_rule_operator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="alerts.rule",
                verbose_name="Regra",
            ),
        ),
    ]
