# Generated by Django 5.0.1 on 2025-11-29 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_preserve_alerts_on_rule_delete"),
        ("cmms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="cmms.workorder",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="ruleparameter",
            name="message_template",
            field=models.TextField(
                help_text="Use {variavel}, {value}, {threshold}, {operator}, {unit} como variáveis",
                verbose_name="Template da Mensagem",
            ),
        ),
    ]
