# Generated by Django 5.0.1 on 2025-11-28 00:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0005_asset_sector_asset_subsection"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome descritivo do template",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do checklist",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text="Lista de itens do checklist em formato JSON",
                        verbose_name="Itens",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o template está disponível para uso",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Template de Checklist",
                "verbose_name_plural": "Templates de Checklist",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Item da Solicitação",
                "verbose_name_plural": "Itens das Solicitações",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Número único da OS (auto-gerado)",
                        max_length=20,
                        unique=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Preventiva"),
                            ("CORRECTIVE", "Corretiva"),
                            ("EMERGENCY", "Emergência"),
                        ],
                        default="CORRECTIVE",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("IN_PROGRESS", "Em Andamento"),
                            ("COMPLETED", "Concluída"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baixa"),
                            ("MEDIUM", "Média"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição detalhada do serviço a ser executado",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "execution_description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do que foi executado (preenchido na conclusão)",
                        verbose_name="Descrição da Execução",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="Data prevista para execução",
                        verbose_name="Data Agendada",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de início da execução",
                        null=True,
                        verbose_name="Iniciado em",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de conclusão",
                        null=True,
                        verbose_name="Concluído em",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas Estimadas",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas Reais",
                    ),
                ),
                (
                    "checklist_responses",
                    models.JSONField(
                        default=dict,
                        help_text="Respostas aos itens do checklist",
                        verbose_name="Respostas do Checklist",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motivo do Cancelamento"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Item da OS",
                "verbose_name_plural": "Itens das OS",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="work_orders/photos/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
            ],
            options={
                "verbose_name": "Foto da OS",
                "verbose_name_plural": "Fotos das OS",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diária"),
                            ("WEEKLY", "Semanal"),
                            ("BIWEEKLY", "Quinzenal"),
                            ("MONTHLY", "Mensal"),
                            ("QUARTERLY", "Trimestral"),
                            ("SEMI_ANNUAL", "Semestral"),
                            ("ANNUAL", "Anual"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Frequência",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "auto_generate",
                    models.BooleanField(
                        default=True,
                        help_text="Se deve gerar OS automaticamente",
                        verbose_name="Geração Automática",
                    ),
                ),
                (
                    "next_execution",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima Execução"
                    ),
                ),
                (
                    "last_execution",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Execução"
                    ),
                ),
                (
                    "work_orders_generated",
                    models.PositiveIntegerField(default=0, verbose_name="OS Geradas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        help_text="Ativos cobertos por este plano",
                        related_name="maintenance_plans",
                        to="assets.asset",
                        verbose_name="Ativos",
                    ),
                ),
                (
                    "checklist_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cmms.checklisttemplate",
                        verbose_name="Template de Checklist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Manutenção",
                "verbose_name_plural": "Planos de Manutenção",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="Número"),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Descrição detalhada do problema ou solicitação",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nova"),
                            ("TRIAGING", "Em Triagem"),
                            ("CONVERTED", "Convertida"),
                            ("REJECTED", "Rejeitada"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_history",
                    models.JSONField(default=list, verbose_name="Histórico de Status"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo da Rejeição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="assets.asset",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="locations.sector",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="locations.subsection",
                        verbose_name="Subseção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
                "ordering": ["-created_at"],
            },
        ),
    ]
