# Generated by Django 5.0.1 on 2025-11-28 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0005_asset_sector_asset_subsection"),
        ("cmms", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.inventoryitem",
                verbose_name="Item de Estoque",
            ),
        ),
        migrations.AddField(
            model_name="requestitem",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cmms.request",
                verbose_name="Solicitação",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="asset",
            field=models.ForeignKey(
                help_text="Equipamento relacionado à OS",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="assets.asset",
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Técnico responsável pela execução",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_work_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="checklist_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cmms.checklisttemplate",
                verbose_name="Template de Checklist",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_work_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="maintenance_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="cmms.maintenanceplan",
                verbose_name="Plano de Origem",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_work_order",
                to="cmms.request",
                verbose_name="Solicitação de Origem",
            ),
        ),
        migrations.AddField(
            model_name="workorderitem",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.inventoryitem",
                verbose_name="Item de Estoque",
            ),
        ),
        migrations.AddField(
            model_name="workorderitem",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cmms.workorder",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AddField(
            model_name="workorderphoto",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enviado por",
            ),
        ),
        migrations.AddField(
            model_name="workorderphoto",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="cmms.workorder",
                verbose_name="Ordem de Serviço",
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["number"], name="cmms_reques_number_53de75_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["status", "-created_at"], name="cmms_reques_status_14868f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["requester", "-created_at"],
                name="cmms_reques_request_1a0938_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["number"], name="cmms_workor_number_3fb838_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["status", "-scheduled_date"],
                name="cmms_workor_status_423f24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["asset", "-created_at"], name="cmms_workor_asset_i_0c780d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["assigned_to", "status"], name="cmms_workor_assigne_7224b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workorderitem",
            unique_together={("work_order", "inventory_item")},
        ),
    ]
