# Generated by Django 5.0.1 on 2025-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="scheduled_date",
            field=models.DateField(
                blank=True,
                help_text="Data prevista para execução",
                null=True,
                verbose_name="Data Agendada",
            ),
        ),
    ]
