# Generated by Django 5.0.1 on 2025-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0003_make_scheduled_date_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="type",
            field=models.CharField(
                choices=[
                    ("PREVENTIVE", "Preventiva"),
                    ("CORRECTIVE", "Corretiva"),
                    ("EMERGENCY", "Emergência"),
                    ("REQUEST", "Solicitação"),
                ],
                default="CORRECTIVE",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
