# Generated by Django 5.0.1 on 2025-12-01 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0004_add_request_type_to_workorder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da categoria",
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da categoria",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#3b82f6",
                        help_text="Cor para identificação visual (hex)",
                        max_length=20,
                        verbose_name="Cor",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria de Procedimento",
                "verbose_name_plural": "Categorias de Procedimentos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título do procedimento",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do procedimento",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("INACTIVE", "Inativo"),
                            ("DRAFT", "Rascunho"),
                            ("ARCHIVED", "Arquivado"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo do procedimento (PDF, MD ou DOCX)",
                        upload_to="procedures/%Y/%m/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("MARKDOWN", "Markdown"),
                            ("DOCX", "Word"),
                        ],
                        default="PDF",
                        max_length=20,
                        verbose_name="Tipo de Arquivo",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número da versão atual",
                        verbose_name="Versão",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags para busca e categorização",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizações"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_procedures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedures",
                        to="cmms.procedurecategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento",
                "verbose_name_plural": "Procedimentos",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Número da Versão"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="procedures/versions/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("MARKDOWN", "Markdown"),
                            ("DOCX", "Word"),
                        ],
                        default="PDF",
                        max_length=20,
                        verbose_name="Tipo de Arquivo",
                    ),
                ),
                (
                    "changelog",
                    models.TextField(
                        blank=True,
                        help_text="Descrição das mudanças nesta versão",
                        verbose_name="Changelog",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cmms.procedure",
                        verbose_name="Procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão de Procedimento",
                "verbose_name_plural": "Versões de Procedimentos",
                "ordering": ["-version_number"],
                "unique_together": {("procedure", "version_number")},
            },
        ),
    ]
