# Generated by Django 5.0.1 on 2025-12-02 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmms", "0005_add_procedure_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da categoria",
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da categoria",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#3b82f6",
                        help_text="Cor para identificação visual (hex)",
                        max_length=20,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="clipboard-list",
                        help_text="Nome do ícone Lucide",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria de Checklist",
                "verbose_name_plural": "Categorias de Checklists",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_checklists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="estimated_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tempo estimado para completar o checklist",
                null=True,
                verbose_name="Tempo Estimado (min)",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Ativo"),
                    ("INACTIVE", "Inativo"),
                    ("DRAFT", "Rascunho"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Quantas vezes este checklist foi utilizado",
                verbose_name="Contador de Uso",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Versão do template", verbose_name="Versão"
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checklist_templates",
                to="cmms.checklistcategory",
                verbose_name="Categoria",
            ),
        ),
    ]
