# Generated by Django 5.0.1 on 2025-10-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_user_avatar_user_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[("12h", "12 hours"), ("24h", "24 hours")],
                default="24h",
                max_length=3,
                verbose_name="Time Format",
            ),
        ),
    ]
