# Generated by Django 5.0.1 on 2025-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_alert_cooldown_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("operator", "Operator"),
                    ("technician", "Technician"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="tenantmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("operator", "Operator"),
                    ("technician", "Technician"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
