version: "3.9"

name: traksense

services:
  emqx:
    image: emqx/emqx:5.8.3
    container_name: emqx
    ports:
      - "1883:1883"    # MQTT (sem TLS no dev)
      - "8883:8883"    # MQTT TLS (não usar no dev)
      - "18083:18083"  # Dashboard EMQX
    environment:
      - EMQX_LOG__TO=console
      - EMQX_NODE__COOKIE=traksense_cookie_dev
      # Dev: TLS desativado por padrão (usar 1883)
    networks: [app-net]

  db:
    image: timescale/timescaledb-ha:pg16
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=traksense
    ports: ["5432:5432"]
    networks: [app-net]

  redis:
    image: redis:7
    container_name: redis
    ports: ["6379:6379"]
    networks: [app-net]

  api:
    build: ../backend
    container_name: api
    env_file:
      - .env.api
    ports: ["8000:8000"]
    depends_on: [db, redis]
    networks: [app-net]
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  ingest:
    build: ../ingest
    container_name: ingest
    env_file:
      - .env.ingest
    depends_on: [emqx, db]
    networks: [app-net]

  # FRONTEND DESLIGADO POR PADRÃO (profile 'frontend')
  frontend:
    profiles: ["frontend"]
    build: ../frontend
    container_name: frontend
    ports: ["5173:5173"]
    networks: [app-net]
    command: ["npm","run","dev","--","--host","0.0.0.0"]

networks:
  app-net:
    driver: bridge
