# Generated by Copilot - 2024
from django.db import migrations, connection


def materialize_cagg_1m(apps, schema_editor):
    """
    Materializa os últimos 14 dias de dados na CAGG ts_measure_1m.
    DEVE rodar fora de transação (atomic=False).
    """
    with connection.cursor() as cursor:
        # Define janela: últimos 14 dias até agora
        cursor.execute("""
            SELECT NOW() - INTERVAL '14 days', NOW();
        """)
        v_start, v_end = cursor.fetchone()
        
        print(f"Materializando ts_measure_1m de {v_start} até {v_end}")
        
        # Força materialização inicial
        cursor.execute("""
            CALL refresh_continuous_aggregate(
                'public.ts_measure_1m',
                %s,
                %s
            );
        """, [v_start, v_end])
        
        print("Materialização completa: ts_measure_1m [14d até now]")


def reverse_materialize(apps, schema_editor):
    """Nenhuma ação no rollback (dados já materializados)"""
    print("Nenhuma ação no rollback (dados já materializados)")


class Migration(migrations.Migration):
    """
    Materializa os últimos 14 dias de dados na CAGG ts_measure_1m.
    
    - CALL refresh_continuous_aggregate com janela explícita
    - Garante que dados históricos sejam agregados imediatamente
    - atomic=False: CALL não pode rodar em transação
    """

    dependencies = [
        ('timeseries', '0011_cagg_1m_retention'),
    ]

    # CRÍTICO: atomic=False para permitir CALL fora de transação
    atomic = False

    operations = [
        migrations.RunPython(
            code=materialize_cagg_1m,
            reverse_code=reverse_materialize,
        ),
    ]
