# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 5m - INDEX
    """

    dependencies = [
        ('timeseries', '0013_cagg_5m_create'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS ts_measure_5m_tenant_device_point_bucket_idx
                ON public.ts_measure_5m (tenant_id, device_id, point_id, bucket DESC);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS public.ts_measure_5m_tenant_device_point_bucket_idx;
            """
        ),
    ]
