# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 5m - REFRESH POLICY
    """

    dependencies = [
        ('timeseries', '0014_cagg_5m_index'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                PERFORM remove_continuous_aggregate_policy('public.ts_measure_5m', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    RAISE NOTICE 'Nenhuma refresh policy para remover';
            END $$;
            
            SELECT add_continuous_aggregate_policy(
                'public.ts_measure_5m',
                start_offset => INTERVAL '90 days',
                end_offset   => INTERVAL '5 minutes',
                schedule_interval => INTERVAL '5 minutes',
                if_not_exists => true
            );
            """,
            reverse_sql="""
            DO $$ 
            BEGIN
                PERFORM remove_continuous_aggregate_policy('public.ts_measure_5m', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    NULL;
            END $$;
            """
        ),
    ]
