# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 5m - ENABLE COMPRESSION
    """

    dependencies = [
        ('timeseries', '0015_cagg_5m_refresh'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER MATERIALIZED VIEW public.ts_measure_5m
            SET (timescaledb.compress = true);
            """,
            reverse_sql="""
            ALTER MATERIALIZED VIEW public.ts_measure_5m
            SET (timescaledb.compress = false);
            """
        ),
    ]
