# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 5m - COMPRESSION POLICY
    """

    dependencies = [
        ('timeseries', '0016_cagg_5m_compress'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                PERFORM remove_compression_policy('public.ts_measure_5m', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    RAISE NOTICE 'Nenhuma compression policy para remover';
            END $$;
            
            SELECT add_compression_policy(
                'public.ts_measure_5m',
                INTERVAL '7 days',
                if_not_exists => true
            );
            """,
            reverse_sql="""
            DO $$ 
            BEGIN
                PERFORM remove_compression_policy('public.ts_measure_5m', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    NULL;
            END $$;
            """
        ),
    ]
