# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 5m - RETENTION POLICY (730 days = 2 years)
    """

    dependencies = [
        ('timeseries', '0017_cagg_5m_compress_policy'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                PERFORM remove_retention_policy('public.ts_measure_5m', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    RAISE NOTICE 'Nenhuma retention policy para remover';
            END $$;
            
            SELECT add_retention_policy(
                'public.ts_measure_5m',
                INTERVAL '730 days',
                if_not_exists => true
            );
            
            DO $$ BEGIN
                RAISE NOTICE 'Retention policy configurada: ts_measure_5m mantém 730d (2 anos)';
            END $$;
            """,
            reverse_sql="""
            DO $$ 
            BEGIN
                PERFORM remove_retention_policy('public.ts_measure_5m', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    NULL;
            END $$;
            """
        ),
    ]
