# Generated by Copilot - 2024
from django.db import migrations, connection


def materialize_cagg_5m(apps, schema_editor):
    """Materializa os últimos 90 dias de dados na CAGG ts_measure_5m"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT NOW() - INTERVAL '90 days', NOW();
        """)
        v_start, v_end = cursor.fetchone()
        
        print(f"Materializando ts_measure_5m de {v_start} até {v_end}")
        
        cursor.execute("""
            CALL refresh_continuous_aggregate(
                'public.ts_measure_5m',
                %s,
                %s
            );
        """, [v_start, v_end])
        
        print("Materialização completa: ts_measure_5m [90d até now]")


def reverse_materialize(apps, schema_editor):
    print("Nenhuma ação no rollback (dados já materializados)")


class Migration(migrations.Migration):
    """
    Materializa os últimos 90 dias de dados na CAGG ts_measure_5m
    """

    dependencies = [
        ('timeseries', '0018_cagg_5m_retention'),
    ]

    atomic = False

    operations = [
        migrations.RunPython(
            code=materialize_cagg_5m,
            reverse_code=reverse_materialize,
        ),
    ]
