# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 1h - REFRESH POLICY
    """

    dependencies = [
        ('timeseries', '0021_cagg_1h_index'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                PERFORM remove_continuous_aggregate_policy('public.ts_measure_1h', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    RAISE NOTICE 'Nenhuma refresh policy para remover';
            END $$;
            
            SELECT add_continuous_aggregate_policy(
                'public.ts_measure_1h',
                start_offset => INTERVAL '1095 days',
                end_offset   => INTERVAL '1 hour',
                schedule_interval => INTERVAL '1 hour',
                if_not_exists => true
            );
            """,
            reverse_sql="""
            DO $$ 
            BEGIN
                PERFORM remove_continuous_aggregate_policy('public.ts_measure_1h', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    NULL;
            END $$;
            """
        ),
    ]
