# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 1h - ENABLE COMPRESSION
    """

    dependencies = [
        ('timeseries', '0022_cagg_1h_refresh'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER MATERIALIZED VIEW public.ts_measure_1h
            SET (timescaledb.compress = true);
            """,
            reverse_sql="""
            ALTER MATERIALIZED VIEW public.ts_measure_1h
            SET (timescaledb.compress = false);
            """
        ),
    ]
