# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 1h - COMPRESSION POLICY (compress chunks > 14 days)
    """

    dependencies = [
        ('timeseries', '0023_cagg_1h_compress'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                PERFORM remove_compression_policy('public.ts_measure_1h', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    RAISE NOTICE 'Nenhuma compression policy para remover';
            END $$;
            
            SELECT add_compression_policy(
                'public.ts_measure_1h',
                INTERVAL '14 days',
                if_not_exists => true
            );
            """,
            reverse_sql="""
            DO $$ 
            BEGIN
                PERFORM remove_compression_policy('public.ts_measure_1h', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    NULL;
            END $$;
            """
        ),
    ]
