# Generated by Copilot - 2024
from django.db import migrations


class Migration(migrations.Migration):
    """
    Continuous Aggregate 1h - RETENTION POLICY (1825 days = 5 years)
    """

    dependencies = [
        ('timeseries', '0024_cagg_1h_compress_policy'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                PERFORM remove_retention_policy('public.ts_measure_1h', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    RAISE NOTICE 'Nenhuma retention policy para remover';
            END $$;
            
            SELECT add_retention_policy(
                'public.ts_measure_1h',
                INTERVAL '1825 days',
                if_not_exists => true
            );
            
            DO $$ BEGIN
                RAISE NOTICE 'Retention policy configurada: ts_measure_1h mantém 1825d (5 anos)';
            END $$;
            """,
            reverse_sql="""
            DO $$ 
            BEGIN
                PERFORM remove_retention_policy('public.ts_measure_1h', if_exists => true);
            EXCEPTION 
                WHEN OTHERS THEN
                    NULL;
            END $$;
            """
        ),
    ]
