# Generated by Copilot - 2024
from django.db import migrations, connection


def materialize_cagg_1h(apps, schema_editor):
    """Materializa os últimos 1095 dias (3 anos) de dados na CAGG ts_measure_1h"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT NOW() - INTERVAL '1095 days', NOW();
        """)
        v_start, v_end = cursor.fetchone()
        
        print(f"Materializando ts_measure_1h de {v_start} até {v_end}")
        
        cursor.execute("""
            CALL refresh_continuous_aggregate(
                'public.ts_measure_1h',
                %s,
                %s
            );
        """, [v_start, v_end])
        
        print("Materialização completa: ts_measure_1h [1095d até now]")


def reverse_materialize(apps, schema_editor):
    print("Nenhuma ação no rollback (dados já materializados)")


class Migration(migrations.Migration):
    """
    Materializa os últimos 1095 dias (3 anos) de dados na CAGG ts_measure_1h
    """

    dependencies = [
        ('timeseries', '0025_cagg_1h_retention'),
    ]

    atomic = False

    operations = [
        migrations.RunPython(
            code=materialize_cagg_1h,
            reverse_code=reverse_materialize,
        ),
    ]
