# Generated by Django 5.0.1 on 2025-11-28 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="Código"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Endereço")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, verbose_name="Estado"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="companies/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Sao_Paulo",
                        max_length=50,
                        verbose_name="Fuso Horário",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gestor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("code",)},
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="Código"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=20, verbose_name="Andar"),
                ),
                (
                    "building",
                    models.CharField(blank=True, max_length=100, verbose_name="Prédio"),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=100, verbose_name="Área"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="locations.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_sectors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supervisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="Código"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Posição"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Referência"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="locations.sector",
                        verbose_name="Setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subseção",
                "verbose_name_plural": "Subseções",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("sector", "code")},
            },
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MANAGER", "Gestor"),
                            ("SUPERVISOR", "Supervisor"),
                            ("TECHNICIAN", "Técnico"),
                            ("EMERGENCY", "Emergência"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="locations.company",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="locations.sector",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="locations.subsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "ordering": ["type", "name"],
            },
        ),
    ]
