# Generated by Django 5.0.1 on 2025-11-29 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together=set(),
        ),
    ]
