# Generated by Django 5.0.1 on 2025-11-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_remove_code_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=50, verbose_name="Estado"),
        ),
    ]
