# Generated by Django 5.0.1 on 2025-11-29 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_increase_state_max_length"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sector",
            unique_together=set(),
        ),
    ]
