# Generated by Django 5.0.1 on 2025-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_remove_sector_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="hvac_units",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Unidades HVAC"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="occupants",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Ocupantes"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="responsible_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nome do Responsável"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="responsible_role",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Cargo do Responsável"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="total_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Área Total (m²)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="CEP"),
        ),
    ]
