# Generated by Django 5.0.1 on 2025-11-29 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_add_operational_fields_to_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone",
        ),
    ]
