# Generated by Django 5.0.1 on 2025-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_remove_contact_fields_from_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="hvac_units",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Unidades HVAC"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="occupants",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Ocupantes"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="responsible_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nome do Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Área (m²)",
            ),
        ),
    ]
