# Generated by Django 5.0.1 on 2025-11-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0007_add_operational_fields_to_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="responsible_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail do Responsável"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="responsible_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefone do Responsável"
            ),
        ),
    ]
