# Generated by Django 5.0.1 on 2025-11-28 00:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cmms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Código"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Ícone"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=20, verbose_name="Cor"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory.inventorycategory",
                        verbose_name="Categoria Pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("IN_PROGRESS", "Em Andamento"),
                            ("COMPLETED", "Concluído"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Agendada"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localização"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="counts",
                        to="inventory.inventorycategory",
                        verbose_name="Categorias",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contagem de Inventário",
                "verbose_name_plural": "Contagens de Inventário",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Código de Barras"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("UN", "Unidade"),
                            ("PC", "Peça"),
                            ("KG", "Quilograma"),
                            ("L", "Litro"),
                            ("M", "Metro"),
                            ("CX", "Caixa"),
                            ("PCT", "Pacote"),
                            ("JG", "Jogo"),
                        ],
                        default="UN",
                        max_length=5,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Estoque Mínimo",
                    ),
                ),
                (
                    "max_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Estoque Máximo",
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Ponto de Reposição",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Custo Unitário",
                    ),
                ),
                (
                    "last_purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Último Custo de Compra",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Localização no Estoque",
                    ),
                ),
                (
                    "shelf",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Prateleira"
                    ),
                ),
                (
                    "bin",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Gaveta/Compartimento"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Fornecedor"
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Código do Fornecedor"
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Lead Time (dias)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inventory/items/",
                        verbose_name="Imagem",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_critical",
                    models.BooleanField(default=False, verbose_name="Item Crítico"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.inventorycategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Estoque",
                "verbose_name_plural": "Itens de Estoque",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Saída"),
                            ("ADJUSTMENT", "Ajuste"),
                            ("TRANSFER", "Transferência"),
                            ("RETURN", "Devolução"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Compra"),
                            ("WORK_ORDER", "Ordem de Serviço"),
                            ("ADJUSTMENT", "Ajuste de Inventário"),
                            ("DAMAGE", "Avaria"),
                            ("EXPIRY", "Vencimento"),
                            ("RETURN_SUPPLIER", "Devolução ao Fornecedor"),
                            ("RETURN_STOCK", "Retorno ao Estoque"),
                            ("TRANSFER", "Transferência"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "quantity_before",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Quantidade Anterior",
                    ),
                ),
                (
                    "quantity_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Quantidade Depois",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Custo Unitário",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referência"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nota Fiscal"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.inventoryitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to="cmms.workorder",
                        verbose_name="Ordem de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Quantidade Esperada",
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Quantidade Contada",
                    ),
                ),
                (
                    "is_counted",
                    models.BooleanField(default=False, verbose_name="Contado"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventorycount",
                        verbose_name="Contagem",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_items",
                        to="inventory.inventoryitem",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Contagem",
                "verbose_name_plural": "Itens de Contagem",
                "unique_together": {("count", "item")},
            },
        ),
    ]
