# Generated by Django 5.0.1 on 2025-11-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL da Imagem"
            ),
        ),
    ]
