# Generated by Django 5.0.1 on 2025-11-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_add_image_url_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="image_url",
            field=models.TextField(
                blank=True,
                help_text="URL ou Data URI da imagem",
                null=True,
                verbose_name="URL da Imagem",
            ),
        ),
    ]
