# Generated by Django 5.0.1 on 2025-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_change_image_url_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Fabricante"
            ),
        ),
    ]
