# Generated by Django 4.2.23 on 2025-10-08 23:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cmd_id",
                    models.TextField(
                        help_text="Identificador único do comando (ex: CMD_20251008_123456)",
                        unique=True,
                    ),
                ),
                ("op", models.TextField(help_text="Operação do comando (ex: SET_PARAM, REBOOT)")),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, help_text="Parâmetros do comando (JSON)"
                    ),
                ),
                (
                    "requested_by",
                    models.UUIDField(
                        blank=True, help_text="ID do usuário que solicitou o comando", null=True
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Momento da solicitação do comando"
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("ACK", "Reconhecido"),
                            ("TIMEOUT", "Timeout"),
                            ("ERROR", "Erro"),
                        ],
                        default="PENDING",
                        help_text="Status do comando (PENDING|ACK|TIMEOUT|ERROR)",
                    ),
                ),
                (
                    "error_msg",
                    models.TextField(
                        blank=True, help_text="Mensagem de erro (se status=ERROR)", null=True
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Dispositivo ao qual este comando pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comando",
                "verbose_name_plural": "Comandos",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["device", "-requested_at"], name="command_device_req_idx"),
                    models.Index(fields=["status", "-requested_at"], name="command_status_req_idx"),
                ],
            },
        ),
    ]
