# Generated by Django 5.0.1 on 2025-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_remove_sensor_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="unit",
            field=models.CharField(
                help_text="Unidade de medida (ex: °C, kW, Pa, %, RPM, m/s2, meters_per_second)",
                max_length=50,
                verbose_name="Unidade",
            ),
        ),
    ]
