# Generated by Django 5.0.1 on 2025-11-24 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_sensor_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="availability",
            field=models.FloatField(
                default=0.0,
                help_text="Porcentagem de uptime nas últimas 24h",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Disponibilidade (%)",
            ),
        ),
    ]
