# Generated by Django 5.0.1 on 2025-11-28 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_device_availability"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                help_text="Setor onde o equipamento está instalado (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="locations.sector",
                verbose_name="Setor",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="subsection",
            field=models.ForeignKey(
                blank=True,
                help_text="Subseção onde o equipamento está instalado (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="locations.subsection",
                verbose_name="Subseção",
            ),
        ),
    ]
