# Generated by Django 5.0.1 on 2025-10-18 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0002_convert_to_hypertable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Device identifier (from MQTT client)",
                        max_length=255,
                    ),
                ),
                (
                    "sensor_id",
                    models.CharField(
                        db_index=True,
                        help_text="Sensor identifier (e.g., temp_001, humidity_002)",
                        max_length=255,
                    ),
                ),
                ("value", models.FloatField(help_text="Numeric sensor reading value")),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional metadata (location, unit, etc.)",
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Measurement timestamp (used for TimescaleDB partitioning)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When record was inserted into database",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading",
                "verbose_name_plural": "Readings",
                "db_table": "reading",
                "ordering": ["-ts"],
            },
        ),
        migrations.RenameIndex(
            model_name="telemetry",
            new_name="telemetry_device__6d4bf8_idx",
            old_name="telemetry_device__idx",
        ),
        migrations.RenameIndex(
            model_name="telemetry",
            new_name="telemetry_topic_5ba748_idx",
            old_name="telemetry_topic_idx",
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["device_id", "sensor_id", "ts"],
                name="reading_device__afd370_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["sensor_id", "ts"], name="reading_sensor__0dc9bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(fields=["id"], name="reading_id_a73f16_idx"),
        ),
    ]
