# Generated by Django 5.0.1 on 2025-11-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0005_add_asset_hierarchy_to_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="asset_tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Asset identifier extracted from MQTT topic (e.g., CHILLER-001)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reading",
            name="site",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Site identifier extracted from MQTT topic (e.g., UMC)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reading",
            name="tenant",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Tenant identifier extracted from MQTT topic (e.g., umc)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="reading",
            constraint=models.UniqueConstraint(
                fields=("device_id", "sensor_id", "ts"),
                name="unique_reading_per_sensor_timestamp",
            ),
        ),
    ]
