# Generated by Django 4.2.23 on 2025-10-08 00:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "schema",
                    models.CharField(
                        default="v1", help_text="Versão do schema JSON (ex: v1)", max_length=20
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Número de versão do template de dashboard"
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        help_text="Estrutura JSON dos painéis (validado contra schema)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_template",
                    models.ForeignKey(
                        help_text="Template de dispositivo ao qual este dashboard pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_templates",
                        to="devices.devicetemplate",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Versão mais nova que substitui esta (se depreciada)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="dashboards.dashboardtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Dashboard",
                "verbose_name_plural": "Templates de Dashboards",
                "ordering": ["device_template", "-version"],
            },
        ),
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "template_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Versão do DashboardTemplate de origem (0 se sem template)",
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        help_text="Estrutura JSON final dos painéis (filtrado por pontos contratados)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        help_text="Device ao qual esta configuração de dashboard pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_config",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Dashboard",
                "verbose_name_plural": "Configurações de Dashboards",
            },
        ),
    ]
